volumes:
  pg_data:

services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: db
    env_file: .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build:
      context: .
    container_name: app
    env_file: .env
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "cd src && python manage.py migrate && gunicorn --bind 0.0.0.0:9000 animal_genetic.wsgi"
    restart: always
